spring:
  application:
    name: wlcp-gameserver
server:
  port: 3333
eureka:
  client:
    serviceUrl:
      defaultZone: http://wlcp-discovery-dev:8761/eureka/
wlcp-api-url:
wlcp-transpiler-url:
wlcp-metrics-url:
security:
  jwt-token: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIifQ.CFsDr9KnYtLCfXkvDyyDyEUdnu5RPPyFQ32jiKMQ8NsbmTfMwVmIeWO0AJxYs8uyPP4txkvy4sP4T6asVN5cIw