spring:
  application:
    name: wlcp-gameserver
  datasource:
    url: jdbc:mysql://localhost:3306/wlcp-gameserver
    username: wlcp
    password: wlcp
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
server:
  port: 3333
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: docker-host
wlcp-api-url: localhost:8082
wlcp-transpiler-url: localhost:8083